#!/bin/bash
cd /tmp/rom # Depends on where source got synced

# Normal build steps
. build/envsetup.sh
lunch lineage_rosy-userdebug
make bacon | tee logs.txt
curl --upload-file ./out/target/product/rosy/*.zip https://transfer.sh/nhalos.zip
